#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S3,     HTSMUX,         sensorI2CCustom9V)
#pragma config(Sensor, S4,     Touch,          sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     LiftA,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     LiftB,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     BackLeft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     FrontLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     FrontRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     BackRight,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    up,                   tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    forebarlink,          tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    Tow,                  tServoStandard)
#pragma DebuggerWindows("joystickGame")
#pragma DebuggerWindows("debugStream")
// #pragma DebuggerWindows("nxtLCDScreen")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "RobotDriveLib.c"

task main()
{
	initializeRobot();
	int Action = 5;
	int LiftAction = 0;
	int Distance = 0;
	int Degrees = 90;
	while(true)
	{
		//display "use right and left arrows to make a selection."
		//display "then press enter"
		while (nNxtButtonPressed != 3)
		{
			//display action
			switch (Action)
			{
			case DRIVE_FORWARD:
				displayTextLine(0,"Action:");
				displayTextLine(1,"DriveForward");
				break;
			case DRIVE_BACK:
				displayTextLine(0,"Action:");
				displayTextLine(1,"DriveBack");
				break;
			case STRAFE_RIGHT:
				displayTextLine(0,"Action:");
				displayTextLine(1,"StrafeRight");
				break;
			case STRAFE_LEFT:
				displayTextLine(0,"Action:");
				displayTextLine(1,"StrafeLeft");
				break;
			case ROTATE_RIGHT: //not working
				displayTextLine(0,"Action:");
				displayTextLine(1,"RotateRight");
				break;
			case ROTATE_LEFT:
				displayTextLine(0,"Action:");
				displayTextLine(1,"RotateLeft");
				break;
			case CONTROL_LIFT:
				displayTextLine(0,"Action:");
				displayTextLine(1,"ControlLift");
				break;
			case SCORE_SERVO:
				displayTextLine(0,"Action:");
				displayTextLine(1,"SCORE_SERVO");
				break;
			case FOREBAR_LINK:
				displayTextLine(0,"Action:");
				displayTextLine(1,"FOREBAR_LINK");
				break;
			case TOW_SERVO:
				displayTextLine(0,"Action:");
				displayTextLine(1,"TOW_SERVO");
				break;
			default:
				Action = 0;
			}
			if(nNxtButtonPressed == 1)
			{
				Action++;
				playSound(soundBlip);
				while(bSoundActive) sleep(1);
			}
			else if(nNxtButtonPressed == 2)
			{
				Action--;
				playSound(soundBlip);
				while(bSoundActive) sleep(1);
			}
			sleep(200);
		}
		displayTextLine(2,"Action Selected");
		playSound(soundBlip);
		while(bSoundActive) sleep(1);
		writeDebugStreamLine("Action: %d",Action);
		writeDebugStreamLine("LiftAction %d",LiftAction);
		writeDebugStreamLine("Degrees: %d",Degrees);
		writeDebugStreamLine("Distance: %d",Distance);
		sleep (2000);
		while (nNxtButtonPressed != 3)
		{
			if (Action == DRIVE_FORWARD || Action == DRIVE_BACK || Action == STRAFE_RIGHT || Action == STRAFE_LEFT)
			{

				displayTextLine(4,"Distance %d Inches", Distance);
				if(nNxtButtonPressed == 1)
				{
					Distance++;
					displayTextLine(4,"Distance %d Inches",Distance);
					playSound(soundBlip);
					while(bSoundActive) sleep(1);
				}
				else if(nNxtButtonPressed == 2)
				{
					Distance--;
					displayTextLine(4,"Distance %d Inches",Distance);
					playSound(soundBlip);
					while(bSoundActive) sleep(1);
				}
			}
			else if (Action == ROTATE_LEFT || Action == ROTATE_RIGHT || Action == SCORE_SERVO || Action == FOREBAR_LINK || Action == TOW_SERVO)
			{
				//rotate action
				displayTextLine(4,"%d Degrees",Degrees);
				if(nNxtButtonPressed == 1)
				{
					Degrees++;
					displayTextLine(4,"%d Degrees",Degrees);
					playSound(soundBlip);
					while(bSoundActive) sleep(1);
				}
				else if(nNxtButtonPressed == 2)
				{
					Degrees--;
					displayTextLine(4,"%d Degrees",Degrees);
					playSound(soundBlip);
					while(bSoundActive) sleep(1);
				}
			}
			else if(Action == CONTROL_LIFT)
			{
				switch (LiftAction)
				{
				case LIFT30CM:
					displayTextLine(4,"Lift30CM");
					break;
				case LIFT60CM:
					displayTextLine(4,"Lift60CM");
					break;
				case LIFT90CM:
					displayTextLine(4,"Lift90CM");
					break;
				case LIFT120CM:
					displayTextLine(4,"Lift120CM");
					break;
				case LIFTDOWN:
					displayTextLine(4,"LiftDown");
					break;
				default:
					LiftAction = 0;
				}
				if(nNxtButtonPressed == 1)
				{
					LiftAction++;
					playSound(soundBlip);
					while(bSoundActive) sleep(1);
				}
				else if(nNxtButtonPressed == 2)
				{
					LiftAction--;
					playSound(soundBlip);
					while(bSoundActive) sleep(1);
				}
			}
			sleep(150);
		}
		playSound(soundBlip);
		while(bSoundActive) sleep(1);
		writeDebugStreamLine("Action: %d",Action);
		writeDebugStreamLine("LiftAction %d",LiftAction);
		writeDebugStreamLine("Degrees: %d",Degrees);
		writeDebugStreamLine("Distance: %d",Distance);
		AutonomousAction(Action,LiftAction,Degrees,Distance);
		sleep(2000);
		eraseDisplay();
	}
}
