#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S4,     LiftDownTouch,  sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     LiftA,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     LiftB,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     BackLeft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     FrontLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     FrontRight,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     BackRight,         tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    up,                   tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    forebarlink,          tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    Tow,                  tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "AutoLib.c"


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  servo[forebarlink]=150;
	servo[Tow]=0;
	servo[servo1]=-80;

  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  initializeRobot();

  waitForStart(); // Wait for the beginning of autonomous phase.

  startTask(Lift);
	startTask(Forebar);
	wait1Msec(500);
	motor[FrontRight]=65;
	motor[BackRight]=65;
	wait1Msec(200);
	motor[FrontLeft]=-50;
	motor[BackLeft]=-50;
	wait1Msec(3400);
	DriveStop();
	wait1Msec(800);

	motor[FrontRight]=50;
	motor[BackRight]=50;
	wait1Msec(60);
	motor[FrontLeft]=-50;
	motor[BackLeft]=-50;
	wait1Msec(900);
	DriveStop();

	wait1Msec(1000);
	servo[servo1]=90;
	wait1Msec(3100);
	servo[servo1]=-80;

	motor[FrontRight]=-50;
	motor[BackRight]=-50;
	wait1Msec(90);
	motor[FrontLeft]=50;
	motor[BackLeft]=50;
	wait1Msec(900);
	DriveStop();

	motor[FrontRight]=50;
	motor[FrontLeft]=50;
	motor[BackRight]=50;
	motor[BackLeft]=50;
	wait1Msec(700);
	DriveStop();

	servo[Tow]=90;
	motor[FrontRight]=-50;
	motor[FrontLeft]=-50;
	motor[BackRight]=50;
	motor[BackLeft]=50;
	wait1Msec(1000);
	DriveStop();
	servo[Tow]=0;
	wait1Msec(1000);

	motor[FrontRight]=50;
	motor[BackRight]=-50;
	wait1Msec(90);
	motor[FrontLeft]=50;
	motor[BackLeft]=-50;
	wait1Msec(800);

	motor[FrontRight]=-50;
	motor[FrontLeft]=-50;
	wait1Msec(430);

	motor[FrontRight]=50;
	motor[FrontLeft]=50;
	wait1Msec(5600);

	motor[FrontRight]=-50;
	motor[FrontLeft]=-50;
	wait1Msec(400);

	motor[FrontRight]=50;
	motor[FrontLeft]=50;
	wait1Msec(700);
	DriveStop();

  while (true)
  {}
}
