#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S3,     HTSMUX,         sensorI2CCustom)
#pragma config(Sensor, S4,     LiftDownTouch,  sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     FrontRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     BackRight,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     BackLeft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     FrontLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     LiftA,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     LiftB,         tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S2_C1_1,    BallRelease,          tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    FourBarLink,          tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    Tow,                  tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "RBButtonLib.h";
RB_Button_State ButtonState;
#include "JoystickDriver.c"
#include "SemiAutoLiftLib.c";
#include "CBRobotMainLib.c"

task main()
{
wait1Msec( 2000 );
	eraseDisplay();
//	nxtDisplayString(0, "12=%d 0=%d -12=%d", RB_abs(12), RB_abs(0), RB_abs(-12));
// nxtDisplayString(2, "12=%d 0=%d -12=%d", RB_sgn(12), RB_sgn(0), RB_sgn(-12));
// nxtDisplayString(2, "12=%d 0=%d -12=%d", RB_constrain(12,0,10), RB_constrain(0,0,10), RB_constrain(-12,0,10));
// nxtDisplayString(0, "2=%d 3=%d 4=%d", RB_map(2,2,4,0,10), RB_map(3,2,4,0,10), RB_map(4,2,4,0,10));
 //nxtDisplayString(0, "1=%d 4=%d 10=%d", RB_map(1,0,10,2,4), RB_map(4,0,10,2,4), RB_map(10,0,10,2,4));
//wait1Msec( 5000 );

	RB_Button_Init(ButtonState);
	startTask(LiftTeleOP);
	startTask(CBDrive);
	startTask(TowMechTeleOP);
	wait1Msec(1200);
	while(true)
	{
		getJoystickSettings(joystick);
		// Add Triggers as Buttons: 13=Right, 14=Left
		short Z2 = joystick.joy1_y2;
		short extraButtons = (Z2>=10 ? 1<<12 : (Z2<=-10 ? 1<<13 : 0));
		RB_Button_addState (ButtonState, joystick.joy1_Buttons | extraButtons);
		wait1Msec(20);
	}
}
