#pragma config(Hubs, S1, HTMotor, HTMotor, HTMotor, HTServo)
#pragma config(Sensor, S2, Touch, sensorTouch)
#pragma config(Sensor, S3, HTSMUX, sensorI2CCustom)
#pragma config(Sensor, S4, LiftZeroSensor, sensorTouch)
#pragma config(Motor, mtr_S1_C1_1, FrontRight, tmotorTetrix, openLoop)
#pragma config(Motor, mtr_S1_C1_2, BackRight, tmotorTetrix, openLoop)
#pragma config(Motor, mtr_S1_C2_1, BackLeft, tmotorTetrix, openLoop)
#pragma config(Motor, mtr_S1_C2_2, FrontLeft, tmotorTetrix, openLoop)
#pragma config(Motor, mtr_S1_C3_1, LiftA, tmotorTetrix, openLoop)
#pragma config(Motor, mtr_S1_C3_2, LiftB, tmotorTetrix, openLoop, reversed)
#pragma config(Servo, srvo_S1_C4_1, up, tServoStandard)
#pragma config(Servo, srvo_S1_C4_2, forebarlink, tServoStandard)
#pragma config(Servo, srvo_S1_C4_3, servo3, tServoNone)
#pragma config(Servo, srvo_S1_C4_4, servo4, tServoNone)
#pragma config(Servo, srvo_S1_C4_5, servo5, tServoNone)
#pragma config(Servo, srvo_S1_C4_6, Tow, tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#define TEST_MOTOR

#include "RBButtonLib.h";
RB_Button_State ButtonState;
#include "SemiAutoLiftLib.c";

task main()
{

	RB_Button_Init(ButtonState);
	nNxtExitClicks = 5;
	startTask(LiftTeleOP);
	while(true)
	{
		// 1 = Gray Rectangle button. 2 = Right Arrow button. 3 = Left Arrow button. 4 = Orange Square button.
		int b=nNxtButtonPressed;
		if (b>0) nNxtExitClicks = 10; // Reset exits again on each use of other button
		RB_Button_addState(ButtonState, (b<0 ? 0 : (1<<b)));
	}
}
