#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     Finger,         sensorTouch)
#pragma config(Sensor, S3,     Sonar,          sensorSONAR)
#pragma config(Sensor, S4,     LiftDownTouch,  sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     LiftA,         tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     LiftB,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     BackLeft,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     FrontLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     FrontRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     BackRight,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    BallRelease,          tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    FourBarLink,          tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    KickStand,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    Tow,                  tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Rover Motion_Librairy.c"


bool StopArc = false;

task ButtonHit()
{
	while (true)
	{
		if (SensorValue[Finger] == true)
		{
			StopArc = true;
		}
		else if (SensorValue[Finger] == false)
		{
			StopArc = false;
		}
	}
}

task main()
{
	setup();
	startTask (ButtonHit);
	wait1Msec(125);
	drive(-50, .1);
	wait1Msec(125);
	straife(50, .6);
	wait1Msec(125);
	drive(-50, 2.9);
	wait1Msec(250);
	servo(KickStand) = 0;
	wait1Msec(250);
	drive(50, .55);
	wait1Msec(1000);
	while (true)
	{
	while(StopArc==false)
	{
		arc(9, 26, 0.25);
	}
	arc(0,0,4);
	}
}
