#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     LiftDownTouch,  sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     LiftA,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     LiftB,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     BackLeft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     FrontLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     FrontRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     BackRight,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    BallRelease,          tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    FourBarLink,          tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    KickStand,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    Tow,                  tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int MotorSpeed = 50;




void DriveStop()//stop function
{
	motor[FrontRight]=0;
	motor[FrontLeft]=0;
	motor[BackRight]=0;
	motor[BackLeft]=0;
}
void Forward () // sets motors to forward
{
	motor[FrontRight]=MotorSpeed;
	motor[BackRight]=MotorSpeed;
	motor[FrontLeft]=-MotorSpeed;
	motor[BackLeft]=-MotorSpeed;
}
void Backward () // sets motors to forward
{
	motor[FrontRight]=-(MotorSpeed + 10);
	motor[BackRight]=-(MotorSpeed + 10);
	motor[FrontLeft]=MotorSpeed;
	motor[BackLeft]=MotorSpeed;
}
void Left() // sets motors to forward
{
	motor[FrontRight]=-MotorSpeed;
	motor[BackRight]=MotorSpeed;
	motor[FrontLeft]=MotorSpeed;
	motor[BackLeft]=-MotorSpeed;
}
void Right() // sets motors to forward
{
	motor[FrontRight]=-MotorSpeed;
	motor[BackRight]=MotorSpeed;
	motor[FrontLeft]=-MotorSpeed;
	motor[BackLeft]=MotorSpeed;
}
void Arc ()
{
	motor[FrontRight]=MotorSpeed;
	motor[BackRight]=MotorSpeed;
	motor[FrontLeft]=-(MotorSpeed-38);
	motor[BackLeft]=-(MotorSpeed-38);
}

task main()
{
	servo[Tow]=0;
	servo[BallRelease]=-80;
	servo[FourBarLink]=300;
	servo[KickStand]=180;

	servo[Tow]=0; // tow arm set down
	Backward ();
 wait1Msec (100);
 Right();
 wait1Msec(600);
 DriveStop();
 Backward ();
 wait1Msec (2750);
 DriveStop ();
	servo[KickStand]=70;
	Forward ();
 wait1Msec (2750);
	Arc ();
	wait1Msec (10000);
}
